name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v0.2.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: pip install toml
      
      - name: Get Version
        id: get_version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('blender_manifest.toml')['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "zip_name=BasedPlayblast.${{ inputs.release_tag }}.zip" >> $GITHUB_OUTPUT
      
      - name: Create ZIP
        run: |
          # Create a temporary directory structure
          mkdir -p addon_files/BasedPlayblast
          
          # Copy the required files for Blender Extensions
          cp __init__.py README.md blender_manifest.toml addon_files/BasedPlayblast/
          
          # Include other necessary files if they exist
          if [ -f "requirements.txt" ]; then
            cp requirements.txt addon_files/BasedPlayblast/
          fi
          
          # Create the zip from the temporary directory
          cd addon_files
          zip -r "../${{ steps.get_version.outputs.zip_name }}" ./*
      
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.get_version.outputs.zip_name }}
          tag_name: ${{ inputs.release_tag }}
          draft: true 